package test.TestStefanHuma;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



public class AddHomeworkTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","Drivers_chrome/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addHomework() {
    driver.get("http://localhost:8080/registro_svn/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("lg2")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("fab");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".buttonLog")).click();
    driver.findElement(By.cssSelector("form:nth-child(1) > .btnSubj:nth-child(3)")).click();
    driver.findElement(By.cssSelector("#flp2 .col-12 .btnSubj")).click();
    driver.findElement(By.id("hmw")).click();
    driver.findElement(By.id("hmw")).sendKeys("Studiare pag 123");
    driver.findElement(By.id("datepick")).click();
    driver.findElement(By.id("datepick")).sendKeys("2020-06-24");
    driver.findElement(By.cssSelector(".side > .btnSubj")).click();
  }
}
